spring:

  cloud:
    # Nacos配置
    nacos:
      # Nacos服务发现与注册配置
      discovery:
        server-addr: 1.14.72.150:8848
# Dubbo配置
dubbo:
  # 通信规则（通信协议和端口）
  protocol:
    name: dubbo
    # (默认20880,-1为随机端口)
    port: -1
    # 序列化方式
  #    serialization: kryo
  # 注册中心的地址
  registry:
    # 挂载到Spring Cloud注册中心
    address: spring-cloud://localhost
  # 连接监控中心
  #  monitor:
  #    protocol: registry
  consumer:
    check: false


# 文件存储配置
aurora:
  file:
    # 本地配置
    local:
      # 上传文件存储在本地的根路径
      path:
      # 资源映射路径前缀
      prefix:
      # 域名或本机访问地址
      domain:
    # Minio 配置信息
    minio:
      url: http://1.14.72.150:9000
      accessKey: aurora_accessKey
      secretKey: aurora_secretKey
      bucketName: aurora
    # 七牛云配置
    qi-niu:
      accessKey: uTOvafM0JSPSgZxYIVsxLf1QEnraVeC2PfpAtkRx
      secretKey: b9LgbcHKqEdhtwYmHn9Af5i2iewXWiNf_XR0J3n_
      # 创建的存储空间名
      bucket: autumnleaves
      # 对应存储空间的访问域名
      path: http://image.guohuaijian.com
      imageMaxSize: 52428800
      imageMaxNameLength: 200
    # AliOSS配置
    alioss:
      endpoint: test
      accessKeyId: aurora_accessKey
      accessKeySecret: aurora_accessKey
      bucketName:
      objectName:
    # fastDfs配置
    fast-dfs:
      # 域名或本机访问地址
      domain:

# oauth2配置
security:
  oauth2:
    client:
      client-id: aurora_client
      client-secret: aurora_secret
      scope: all
      # 获取token地址
      access-token-uri: http://localhost:8081/oauth/token
      # 获取授权code
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      # 校验token
      token-info-uri: http://localhost:8081/oauth/check_token
    authorization:
      # 校验token
      check-token-access: http://localhost:8081/oauth/check_token
      # 放行地址
    ignore:
      urls: /file/upload

# 端点检查
management:
  endpoint:
    health:
      enabled: true

# 日志配置
logging:
  level:
    com.aurora: debug
    org.springframework: info
