# 文件存储配置
file:
  path:
  prefix:
  domain:

# Minio 配置信息
minio:
  url:
  accessKey:
  secretKey:
  bucketName:

# fastDfs配置
fdfs:
  domain:

# 七牛云配置
qiniuyun:
  accessKey: uTOvafM0JSPSgZxYIVsxLf1QEnraVeC2PfpAtkRx
  secretKey: b9LgbcHKqEdhtwYmHn9Af5i2iewXWiNf_XR0J3n_
  # 创建的存储空间名
  bucket: autumnleaves
  # 对应存储空间的访问域名
  path: http://image.guohuaijian.com
  imageMaxSize: 52428800
  imageMaxNameLength: 200

# AliOSS配置
alioss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  objectName:
