spring:

  cloud:
    # Nacos配置
    nacos:
      # Nacos服务发现与注册配置
      discovery:
        server-addr: localhost:8848

    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # aurora-auth
        - id: aurora-auth
          uri: lb://aurora-auth
          predicates:
            - Path=/dev-api/oauth/**
          filters:
            - StripPrefix=1
        # aurora-system
        - id: aurora-system
          uri: lb://aurora-system
          predicates:
            - Path=/dev-api/system/**
          filters:
            - StripPrefix=1
        # aurora-admin
        - id: aurora-admin
          uri: lb://aurora-admin
          predicates:
            - Path=/dev-api/admin/**
          filters:
            - StripPrefix=1

# 端点检查
management:
  endpoint:
    health:
      enabled: true
