spring:

  cloud:
    # Nacos配置
    nacos:
      # Nacos服务发现与注册配置
      discovery:
        server-addr: 1.14.72.150:8848

  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.72.150:3306/aurora_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 564559079

  # redis配置
  redis:
    # 地址
    host: 1.14.72.150
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# Dubbo
dubbo:
  # 通信规则（通信协议和端口）
  protocol:
    name: dubbo
    # (默认20880,-1为随机端口)
    port: -1
    # 序列化方式
  #    serialization: kryo
  # 注册中心的地址
  registry:
    # 挂载到Spring Cloud注册中心
    address: spring-cloud://localhost
  # 连接监控中心
  #  monitor:
  #    protocol: registry
  consumer:
    check: false

# oauth配置
security:
  oauth2:
    # 放行地址
    ignore:
      urls:
        - /oauth/**
        - /actuator/**
        - www.baidu.com
        - /token/**
# 端点检查
management:
  endpoint:
    health:
      enabled: true

# 日志配置
logging:
  level:
    com.aurora: debug
    org.springframework: warn
