server:
  # 端口
  port: 8098
  servlet:
    # 应用的访问路径
    context-path:

spring:
  # 服务名
  application:
    name: aurora-file
  profiles:
    # 激活配置
    active: dev

  main:
    allow-bean-definition-overriding: true

