server:
  # 端口
  port: 8082
  servlet:
    # 应用的访问路径
    context-path:

spring:
  # 服务名
  application:
    name: aurora-system
  profiles:
    # 激活配置
    active: dev

  main:
    allow-bean-definition-overriding: true

# 项目相关配置
aurora:
  # 名称
  name: AuroraBlog
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 文件路径 示例（ Windows配置D:/aurora/uploadPath，Linux配置 /home/aurora/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

