spring:

  cloud:
    # Nacos配置
    nacos:
      # Nacos服务发现与注册配置
      discovery:
        server-addr: 1.14.72.150:8848

# Dubbo
dubbo:
  # 通信规则（通信协议和端口）
  protocol:
    name: dubbo
    # (默认20880,-1为随机端口)
    port: -1
    # 序列化方式
  #    serialization: kryo
  # 注册中心的地址
  registry:
    # 挂载到Spring Cloud注册中心
    address: spring-cloud://localhost
  # 连接监控中心
  #  monitor:
  #    protocol: registry
  consumer:
    check: false

# 日志配置
logging:
  level:
    com.aurora: debug
    org.springframework: warn

# JWT配置
#jwt:
#  # 密匙Key
#  secret: JWTSecret,C3Stones
#  # HeaderKey
#  tokenHeader: Authorization
#  # Token前缀
#  tokenPrefix: Bearer
#  # 过期时间，单位秒
#  expiration: 86400
#  # 配置白名单（不需要认证）
#  antMatchers: /login/**,/register/**,/static/**
