server:
  port: 8080

spring:
  #服务名
  application:
    name: aurora-auth

  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 564559079

# JWT配置
jwt:
  # 密匙Key
  secret: JWTSecret,C3Stones
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 86400
  # 配置白名单（不需要认证）
  antMatchers: /login/**,/register/**,/static/**

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Dubbo
dubbo:
  #通信规则（通信协议和端口）
  protocol:
    name: Triple
    #(默认20880,-1为随机端口)
    port: -1
  #注册中心的地址和协议
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  #连接监控中心
  monitor:
    protocol: registry
  scan:
    base-packages: com.aurora.auth.service.impl
